# Use root/example as user/password credentials
version: '3.1'

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    links:
      - "php:php"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: ./php-fpm
    volumes:
      - ./src:/var/www

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: M*1234567
      MYSQL_DATABASE: magento23
      MYSQL_USER: magento_user
      MYSQL_PASSWORD: M*1234567
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080